import { z } from 'zod'

// The three roles from PRD §3. Used everywhere a role crosses a boundary.
export const roleSchema = z.enum(['admin', 'supervisor', 'enumerator'])

// A profile row as read back from Supabase (PRD §6). Validate on every read.
export const profileSchema = z.object({
  id: z.string().uuid(),
  email: z.string().email(),
  full_name: z.string().nullable(),
  role: roleSchema,
  active: z.boolean(),
  created_at: z.string(),
})

// Login form input.
export const loginSchema = z.object({
  email: z.string().email('Enter a valid email address.'),
  password: z.string().min(1, 'Password is required.'),
})

// Form creation / upload inputs.
export const createFormSchema = z.object({
  title: z.string().trim().min(1, 'Title is required.').max(200),
  description: z.string().trim().max(2000).optional().default(''),
})

// Form builder (create-from-scratch, §5.5 — the alternative to XLSForm upload).
// Field types the builder exposes, each mapping 1:1 to a runtime question type the renderer
// (src/components/form-fill/field-input.jsx) already handles.
export const BUILDER_FIELD_TYPES = [
  'text',
  'integer',
  'decimal',
  'select_one',
  'select_multiple',
  'date',
  'note',
  'image',
  'geopoint',
]

const builderChoiceSchema = z.object({
  label: z.string().trim().min(1, 'Every option needs a label.').max(200),
})

export const builderFieldSchema = z
  .object({
    type: z.enum(BUILDER_FIELD_TYPES),
    label: z.string().trim().min(1, 'Every question needs a label.').max(500),
    // Optional data-column name; server auto-generates a safe unique name when blank.
    name: z
      .string()
      .trim()
      .regex(/^[a-zA-Z_][a-zA-Z0-9_]*$/, 'Names use letters, numbers and underscores, and start with a letter.')
      .max(64)
      .optional()
      .or(z.literal('')),
    hint: z.string().trim().max(1000).optional().default(''),
    required: z.boolean().default(false),
    choices: z.array(builderChoiceSchema).default([]),
  })
  .refine((f) => !['select_one', 'select_multiple'].includes(f.type) || f.choices.length >= 1, {
    message: 'Choice questions need at least one option.',
    path: ['choices'],
  })

export const builderFormSchema = z.object({
  title: z.string().trim().min(1, 'Form title is required.').max(200),
  description: z.string().trim().max(2000).optional().default(''),
  fields: z.array(builderFieldSchema).min(1, 'Add at least one question.'),
})

// A single assignment toggle row submitted from the form-detail UI.
export const assignmentInputSchema = z.object({
  user_id: z.string().uuid(),
  can_fill: z.boolean(),
  can_review: z.boolean(),
})

export const assignmentsSchema = z.array(assignmentInputSchema)

// A submission attachment reference (the file already lives in storage).
export const attachmentInputSchema = z.object({
  question_name: z.string().min(1),
  storage_path: z.string().min(1),
  mime_type: z.string().optional(),
  size_bytes: z.number().int().nonnegative().optional(),
})

// Invite a new user (admin only, §7 screen 6).
export const inviteUserSchema = z.object({
  email: z.string().trim().email('Enter a valid email.'),
  full_name: z.string().trim().min(1, 'Name is required.').max(200),
  role: roleSchema,
})

// Review action input (§8). Flag and reject require a comment.
export const reviewActionSchema = z.enum(['approve', 'flag', 'reject'])
export const reviewInputSchema = z
  .object({
    submission_id: z.string().uuid(),
    action: reviewActionSchema,
    comment: z.string().trim().max(2000).optional().default(''),
  })
  .refine((v) => v.action === 'approve' || v.comment.length > 0, {
    message: 'A comment is required to flag or reject.',
    path: ['comment'],
  })

// The submission POST body. `id` is generated by the browser for idempotency (§6).
export const submissionInputSchema = z.object({
  id: z.string().uuid(),
  form_version_id: z.string().uuid(),
  data: z.record(z.string(), z.any()).default({}),
  started_at: z.string().optional(),
  duration_seconds: z.number().int().nonnegative().optional(),
  geo_lat: z.number().optional(),
  geo_lng: z.number().optional(),
  user_agent: z.string().max(500).optional(),
  attachments: z.array(attachmentInputSchema).default([]),
})

/** @typedef {z.infer<typeof roleSchema>} Role */
/** @typedef {z.infer<typeof profileSchema>} Profile */
